import { SERVICE_NAME } from "@mcp-foundry/shared";
import type { ServerSpec } from "@mcp-foundry/spec";
import { toSlug } from "../slug.js";
import type { Template } from "./types.js";

// Curated, hand-verified spec wrapping the free, keyless Frankfurter
// exchange-rate API. Real stock-quote APIs require an API key, which the
// v1 DSL cannot carry safely (see envelope/check-envelope.ts) — this
// template covers the same "financial lookup" intent with a keyless source.
// The target currency is fixed to KRW so every response field path is
// static (a DSL field selector cannot follow a param-dependent JSON key).
const BASE_SPEC: ServerSpec = {
  name: "Currency Exchange",
  slug: "currency-exchange",
  description: `A read-only currency exchange rate server (to KRW) generated by ${SERVICE_NAME}, backed by the free Frankfurter API.`,
  mcpVersion: "2025-06-18",
  tools: [
    {
      name: "get_exchange_rate_to_krw",
      title: "Get exchange rate to KRW",
      description: `Get the current exchange rate from a currency to KRW via ${SERVICE_NAME}, backed by the free Frankfurter API.`,
      annotations: {
        title: "Get exchange rate to KRW",
        readOnlyHint: true,
        destructiveHint: false,
        idempotentHint: true,
        openWorldHint: true,
      },
      inputSchema: {
        type: "object",
        properties: { from: { type: "string", description: "3-letter source currency code, e.g. \"USD\"." } },
        required: ["from"],
        additionalProperties: false,
      },
      request: {
        method: "GET",
        urlTemplate: "https://api.frankfurter.app/latest",
        headers: [{ name: "accept", value: "application/json" }],
        query: [
          { key: "from", param: "from" },
          { key: "to", value: "KRW" },
        ],
        body: null,
      },
      response: {
        fieldSelectors: [
          { name: "base", path: "base" },
          { name: "date", path: "date" },
          { name: "rateKrw", path: "rates.KRW" },
        ],
        markdownTemplate: "**Exchange Rate**\n\n1 {{base}} = {{rateKrw}} KRW (as of {{date}})",
      },
      cacheTtlSeconds: 60,
    },
    {
      name: "convert_amount_to_krw",
      title: "Convert an amount to KRW",
      description: `Convert an amount from a currency to KRW via ${SERVICE_NAME}, backed by the free Frankfurter API.`,
      annotations: {
        title: "Convert an amount to KRW",
        readOnlyHint: true,
        destructiveHint: false,
        idempotentHint: true,
        openWorldHint: true,
      },
      inputSchema: {
        type: "object",
        properties: {
          from: { type: "string", description: "3-letter source currency code, e.g. \"USD\"." },
          amount: { type: "number", description: "Amount to convert, e.g. 100." },
        },
        required: ["from", "amount"],
        additionalProperties: false,
      },
      request: {
        method: "GET",
        urlTemplate: "https://api.frankfurter.app/latest",
        headers: [{ name: "accept", value: "application/json" }],
        query: [
          { key: "from", param: "from" },
          { key: "amount", param: "amount" },
          { key: "to", value: "KRW" },
        ],
        body: null,
      },
      response: {
        fieldSelectors: [
          { name: "amount", path: "amount" },
          { name: "base", path: "base" },
          { name: "date", path: "date" },
          { name: "rateKrw", path: "rates.KRW" },
        ],
        markdownTemplate: "**Currency Conversion**\n\n{{amount}} {{base}} = {{rateKrw}} KRW (as of {{date}})",
      },
      cacheTtlSeconds: 60,
    },
    {
      name: "get_historical_exchange_rate_to_krw",
      title: "Get historical exchange rate to KRW",
      description: `Get a historical exchange rate from a currency to KRW on a given date via ${SERVICE_NAME}, backed by the free Frankfurter API.`,
      annotations: {
        title: "Get historical exchange rate to KRW",
        readOnlyHint: true,
        destructiveHint: false,
        idempotentHint: true,
        openWorldHint: true,
      },
      inputSchema: {
        type: "object",
        properties: {
          date: { type: "string", description: "Date in YYYY-MM-DD format, e.g. \"2025-01-15\"." },
          from: { type: "string", description: "3-letter source currency code, e.g. \"USD\"." },
        },
        required: ["date", "from"],
        additionalProperties: false,
      },
      request: {
        method: "GET",
        urlTemplate: "https://api.frankfurter.app/{date}",
        headers: [{ name: "accept", value: "application/json" }],
        query: [
          { key: "from", param: "from" },
          { key: "to", value: "KRW" },
        ],
        body: null,
      },
      response: {
        fieldSelectors: [
          { name: "base", path: "base" },
          { name: "date", path: "date" },
          { name: "rateKrw", path: "rates.KRW" },
        ],
        markdownTemplate: "**Historical Exchange Rate**\n\n1 {{base}} = {{rateKrw}} KRW on {{date}}",
      },
      cacheTtlSeconds: 300,
    },
  ],
};

export const currencyTemplate: Template = {
  id: "currency",
  keywords: ["currency", "exchange rate", "환율", "환전"],
  buildSpec: (overrides) => {
    const base = structuredClone(BASE_SPEC);
    if (!overrides?.name) return base;
    return { ...base, name: overrides.name, slug: toSlug(overrides.name) };
  },
};
