import { SERVICE_NAME } from "@mcp-foundry/shared";
import type { ServerSpec } from "@mcp-foundry/spec";
import { toSlug } from "../slug.js";
import type { Template } from "./types.js";

// Curated, hand-verified spec wrapping the free, keyless Wikipedia REST API.
// Kept as a plain object literal (not a fixture import) since it lives in
// this package rather than packages/spec.
const BASE_SPEC: ServerSpec = {
  name: "Wikipedia Search",
  slug: "wikipedia-search",
  description: `A read-only Wikipedia search and lookup server generated by ${SERVICE_NAME}, backed by the free Wikipedia REST API.`,
  mcpVersion: "2025-06-18",
  tools: [
    {
      name: "search_wikipedia",
      title: "Search Wikipedia",
      description: `Search Wikipedia for articles matching a query via ${SERVICE_NAME}, backed by the free Wikipedia REST API. Returns up to 3 matching page titles and short descriptions.`,
      annotations: {
        title: "Search Wikipedia",
        readOnlyHint: true,
        destructiveHint: false,
        idempotentHint: true,
        openWorldHint: true,
      },
      inputSchema: {
        type: "object",
        properties: { query: { type: "string", description: "Search text, e.g. \"Alan Turing\"." } },
        required: ["query"],
        additionalProperties: false,
      },
      request: {
        method: "GET",
        urlTemplate: "https://en.wikipedia.org/w/rest.php/v1/search/page",
        headers: [{ name: "accept", value: "application/json" }],
        query: [
          { key: "q", param: "query" },
          { key: "limit", value: "3" },
        ],
        body: null,
      },
      response: {
        fieldSelectors: [
          { name: "result1Title", path: "pages[0].title" },
          { name: "result1Description", path: "pages[0].description" },
          { name: "result2Title", path: "pages[1].title" },
          { name: "result2Description", path: "pages[1].description" },
          { name: "result3Title", path: "pages[2].title" },
          { name: "result3Description", path: "pages[2].description" },
        ],
        markdownTemplate:
          "**Wikipedia Search Results**\n\n1. **{{result1Title}}** — {{result1Description}}\n2. **{{result2Title}}** — {{result2Description}}\n3. **{{result3Title}}** — {{result3Description}}",
      },
      cacheTtlSeconds: 60,
    },
    {
      name: "get_wikipedia_summary",
      title: "Get Wikipedia article summary",
      description: `Get the summary of a Wikipedia article by exact title via ${SERVICE_NAME}, backed by the free Wikipedia REST API.`,
      annotations: {
        title: "Get Wikipedia article summary",
        readOnlyHint: true,
        destructiveHint: false,
        idempotentHint: true,
        openWorldHint: true,
      },
      inputSchema: {
        type: "object",
        properties: { title: { type: "string", description: "Exact Wikipedia article title, e.g. \"Alan_Turing\"." } },
        required: ["title"],
        additionalProperties: false,
      },
      request: {
        method: "GET",
        urlTemplate: "https://en.wikipedia.org/api/rest_v1/page/summary/{title}",
        headers: [{ name: "accept", value: "application/json" }],
        query: [],
        body: null,
      },
      response: {
        fieldSelectors: [
          { name: "title", path: "title" },
          { name: "description", path: "description" },
          { name: "extract", path: "extract" },
        ],
        markdownTemplate: "**{{title}}**\n\n{{description}}\n\n{{extract}}",
      },
      cacheTtlSeconds: 300,
    },
    {
      name: "get_random_wikipedia_article",
      title: "Get a random Wikipedia article",
      description: `Get a random Wikipedia article summary via ${SERVICE_NAME}, backed by the free Wikipedia REST API.`,
      annotations: {
        title: "Get a random Wikipedia article",
        readOnlyHint: true,
        destructiveHint: false,
        idempotentHint: false,
        openWorldHint: true,
      },
      inputSchema: {
        type: "object",
        properties: {},
        required: [],
        additionalProperties: false,
      },
      request: {
        method: "GET",
        urlTemplate: "https://en.wikipedia.org/api/rest_v1/page/random/summary",
        headers: [{ name: "accept", value: "application/json" }],
        query: [],
        body: null,
      },
      response: {
        fieldSelectors: [
          { name: "title", path: "title" },
          { name: "description", path: "description" },
          { name: "extract", path: "extract" },
        ],
        markdownTemplate: "**Random Article: {{title}}**\n\n{{description}}\n\n{{extract}}",
      },
      // Deliberately no cacheTtlSeconds: caching would defeat "random".
    },
  ],
};

export const searchTemplate: Template = {
  id: "search",
  keywords: ["wikipedia", "search", "검색", "위키"],
  buildSpec: (overrides) => {
    const base = structuredClone(BASE_SPEC);
    if (!overrides?.name) return base;
    return { ...base, name: overrides.name, slug: toSlug(overrides.name) };
  },
};
